sudo: required
services:
- docker
script:
- make
branches:
  only:
  - master
env:
  global:
  - secure: ICC8sFrdbfhxcBCFKJJizcbwJhGe2aUXs3INPsRkDr/L6520hJUDqkp+7mEFJVEITPsideiIbbr/5ikuJDyRcD54ZE0IT06wIrK3Z/pCRN5jxB15869uk3d2ky+03OpIEx7KhfLJHR9bbKiM1OtLZETf6gwkNpXt4dBefwnZpNfjE9+g4H5ngnlTuX1FHj3X6HazUwBqcAlRbwAwNtBW0iYWEPJSGewDWUYzo36ut2/1eRiByxjI8WgacLEX/8TAWFyHAYdL/fz6L4ELNGypjHD6NtFvOOBk1UCXIz1RJ269SthRRtDkbMqdAdWZxtEAsg6HJ7TvWpVUz9FO/GYJRd8GCY2+Ei+jBoB2rzyMmTj98bMbNJvYPeIXgSEXa9B0acD3IhAARXwV2ka9YO8fb9jrOLHm6luYPMrtIgmAzyHkPA7SJZrir25kS3K6ceSp1ZieyTQ5jvHGRPYpW6Ti5qklIhANa739UZrLP5LLLRITtrXAp3py7mOD8TKY3M/SnOR1OZl9zo3CR2ql9yl42fOwXDvl7KR6pgK2luXHUWeQkeEZoJVny2kisRDauUH9e3eWjW3ShBfoGkPOzR4OVC810yRyOU7BZmutPl391BmaEo0K0/fSg0aggAoosRYdRtT2Rico2DKr48K8l3i56fnd9DYZ2fCsomJfMuKoHpU=
  - secure: iQrb4aoU2feOgh9fCjx7ImlhUKAGBbN+r5673buTZYJ/cAWABs2akCoQn1+wuobktCZDJI1JQIfzK0P7fJDa8RiYiA8v4pNRqkKiECSuW2X99S3ddwuhybdNf8y3kg7taWnpo3Tnb6gvULxaPUjjy6PrSaXXvzwhSFuELTPIjnbEyWaE/BxrSUxYk0QVwk2Kn7Tbxnjs+depPnyk7dNDPtK3zT8sK323v29VBAtpxjP0LCzHnUwgkrjJeD/usSc7RXHeYYvVfB8An01Q4usQqlCt9h7O7U1ujXNi9LhDLyTax6xKrkKsafcN8fVSWsj8aHeyzqUvuOpBltg9EWNUhTr3W/mYP/l9+WMTLpyg/RlUdw3PZpKVJsG9HRJFDUEFphuCFtoJZ2Zsag9rR5tDkk0TW6ehfwYFwySOFTck7vn/SrN8NLYecl0eQg13o3ejLqQLWthEaTeRE9SUHNJuN6KhtPwDGhIqEsyxkMkoanbHr2I8gba44t6E0ItU+0ERt7puFUNyELxyajv8KF6K8d2JuauwhBa8/Yp2fMz1KUGTXN/sJ1WiKFpNqQpuqmsoKzAg2zkzi6eahSLWfQnEypoBOamjkD2stuIONo6vy2GjWEOu5aw5w2N75Pm10/4Qx9GnxLiALBMPXObk5H5ahh4f8bvEaZCmxDEMbOsjDlo=
