version: '2'
services:
  server:
    build: js
    image: server
    ports:
     - 8080:8080
     - 5858:5858
    volumes:
     - ./js:/work/ # For dev-ing
     - /work/images
     - /work/node_modules
    environment:
     MONGO_HOST: mongo
     WEBDRIVER_HOST: webdriver
     SERVER_HOST: server
  prediction:
   build: tensor
   image: prediction
   volumes:
    - prediction:/work/runs
  mongo:
    image: mongo:3.3.10
    ports:
     - 27017:27017
    volumes:
    - db:/data/db
  healthcheck:
    image: wait-for-http
    command: http://server:8080/api/items/
  webdriver:
    image: webdriver
    volumes:
    - /dev/shm:/dev/shm 
    ports:
     - 4444:4444
volumes:
  db: {}
  prediction: {}