version: '2'
services:
  server:
    build: js
    image: server
    ports:
     - 8080:8080
     - 5858:5858
    volumes:
     - ./js/src:/work/src/ # For dev-ing
    environment:
     MONGO_HOST: mongo
     WEBDRIVER_HOST: webdriver
     SERVER_HOST: server
     PREDICTOR_HOST: predictor
     PREDICTOR_PORT: 8080
  predictor:
   build: tensor
   image: predictor
   ports:
    - 8081:8080
   volumes:
    - prediction:/work/runs
  mongo:
    image: mongo:3.3.10
    ports:
     - 27017:27017
    volumes:
    - db:/data/db
  healthcheck:
    image: wait-for-http
    command: http://server:8080/api/items/
  webdriver:
    image: webdriver
    volumes:
    - /dev/shm:/dev/shm 
    ports:
     - 4444:4444
volumes:
  db: {}
  prediction: {}