version: '2'
services:
  server:
    build: .
    image: server
    ports:
     - 8080:8080
     - 5858:5858
    volumes:
     - ./:/work/
     - /work/node_modules
    environment:
     MONGO_HOST: mongo
     WEBDRIVER_HOST: webdriver
     SERVER_HOST: server
     SLACK_TOKEN:
     TEST_SLACK_TOKEN:
  mongo:
    image: mongo:3.3.10
    ports:
     - 27017:27017
  healthcheck:
    image: wait-for-http
    command: http://server:8080/api/items/
  webdriver:
    image: webdriver
    volumes:
    - /dev/shm:/dev/shm 
    ports:
     - 4444:4444